### PR TITLE
force resync on initialisiation for all run control calcs

### PR DESCRIPTION
**Pull request by rerpha**

### CODE REVIEW

**Comment by rerpha** [comment]
alternatively could just PINI the calc itself

**Comment by FreddieAkeroyd** [comment]
I think a PINI on the calc record `$(P)CS:$(MODE):_CALC2` may be clearer, the issue would appear to be that `On Change` in `_CALC` does not cause an initial process if there are 0 elements out of range, but it may need to clear a previous state or something like that. Thanks for locating the issue.

**Comment by FreddieAkeroyd** [comment]
Is it worth us hotfixing onto instruments in easter shutdown? We haven't seen many instances of this, but it is an annoying thing when it does happen.

**Comment by rerpha** [comment]
> Is it worth us hotfixing onto instruments in easter shutdown? We haven't seen many instances of this, but it is an annoying thing when it does happen.

Probably OK i'd say - very much an edge case and I think i've only ever seen it on OFFSPEC. I think if it happens again before the fix is deployed we can just do https://github.com/ISISComputingGroup/ibex_developers_manual/wiki/Run-control#troubleshooting

**Review by FreddieAkeroyd — APPROVED** [review]

**Pull request merged**
