### PR TITLE
Add generic control and action structure

### PR DESCRIPTION
**Pull request by FreddieAkeroyd**
See ISISComputingGroup/IBEX#3949

### CODE REVIEW

**Review by Tom-Willemsen — COMMENTED** [review]
- [ ] Can we test this via the IOC test framework to check the DB records do what we expect
- [ ] Can we add some documentation about how to set up alerts (I couldn't find anything on the wiki)
- [x] There is very significant duplication between the `gencontrol` and `runcontrol` DB files. We should refactor now to eliminate this duplication before it starts causing problems - otherwise we are just adding technical debt for later.
- [x] I can't find anywhere that loads `gencontrol.db` or `gencontrolMgr.db` other than `ioctestRunControl` which we don't use. Where is it meant to be loaded from? Presumably the main run control ioc...

**Comment by FreddieAkeroyd** [comment]
gencontrol can already replace runcontrol, just didn't want to delete the old files at this point

**Comment by FreddieAkeroyd** [comment]
Wiki page created with link to documentation in IOC area https://github.com/ISISComputingGroup/IBEX/wiki/Email-Text-Alerts-from-IOCS

**Comment by FreddieAkeroyd** [comment]
gencontrol.db etc is loaded by RUNCTRL ioc which I hotfixed on LOQ

**Comment by FreddieAkeroyd** [comment]
the substitutions file in the run control IOC Db directory uses gencontrol / gencontrolMgr to build runcontrol.db etc.

**Comment by FreddieAkeroyd** [comment]
System tests in ISISComputingGroup/system_tests#19

**Pull request merged**
